language: java

dist: xenial
sudo: false

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - redis
  - docker

env:
  global:
    - LUAROCKS=3.0.4
    - OPENSSL=1.1.1b
    - CASSANDRA_BASE=2.2.12
    - CASSANDRA_LATEST=3.9
    - OPENRESTY_BASE=1.13.6.2
    - OPENRESTY_LATEST=1.13.6.2
    - OPENRESTY=$OPENRESTY_BASE
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
    - BUSTED_ARGS="-o gtest -v --exclude-tags=flaky,ipv6"
    - PLUGIN_NAME=myplugin
    - KONG_TEST_PLUGINS=bundled,$PLUGIN_NAME
    - KONG_PLUGINS=bundled,$PLUGIN_NAME

  matrix:
    - OPENRESTY=$OPENRESTY_BASE
      CASSANDRA=$CASSANDRA_BASE
    - OPENRESTY=$OPENRESTY_LATEST
      CASSANDRA=$CASSANDRA_LATEST

before_install:
  - source setup_env.sh
  - git clone https://github.com/Kong/kong.git kong-ce
  - source kong-ce/setup_env.sh

install:
  - luarocks make
  - cd kong-ce
  - make dev
  - createuser --createdb kong
  - createdb -U kong kong_tests

script:
  - bin/busted $BUSTED_ARGS ../spec

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository